% Read trajectory data generated by Barnes-Hut simulation
traj = readtable('../data/trajectory.csv');

% Extract columns directly by header name
step_col = traj.step;
x_col    = traj.x;
y_col    = traj.y;
steps    = unique(step_col);

fig = figure('Color', [0.03 0.03 0.05], 'Position', [100, 100, 700, 700], 'MenuBar', 'none');
gif_name = '../plots/nbody_animation.gif';

for i = 1:length(steps)
    s = steps(i);
    idx = (step_col == s);
    
    xs = x_col(idx);
    ys = y_col(idx);
    
    % Radial distance from center for plasma color map
    r = sqrt(xs.^2 + ys.^2);
    
    clf;
    scatter(xs, ys, 10, r, 'filled', 'MarkerFaceAlpha', 0.65);
    colormap(flipud(hot));
    clim([0, 1.8]);
    
    % Spatial limits for cold collapse view
    xlim([-2.2 2.2]);
    ylim([-2.2 2.2]);
    axis square;
    
    % Axes styling
    ax = gca;
    ax.Color = [0.02 0.02 0.04];
    ax.XColor = [0.75 0.75 0.75];
    ax.YColor = [0.75 0.75 0.75];
    grid on;
    ax.GridColor = [0.3 0.3 0.35];
    ax.GridAlpha = 0.4;
    
    xlabel('X Position', 'Color', [0.9 0.9 0.9], 'FontSize', 11, 'FontWeight', 'bold');
    ylabel('Y Position', 'Color', [0.9 0.9 0.9], 'FontSize', 11, 'FontWeight', 'bold');
    title(sprintf('Cold Collapse Simulation  |  Step: %d', s), ...
          'Color', [1 0.9 0.6], 'FontSize', 13, 'FontWeight', 'bold');
    
    drawnow;
    
    % Write frame to GIF
    frame = getframe(fig);
    im = frame2im(frame);
    [imind, cm] = rgb2ind(im, 256);
    
    if i == 1
        imwrite(imind, cm, gif_name, 'gif', 'Loopcount', inf, 'DelayTime', 0.05);
    else
        imwrite(imind, cm, gif_name, 'gif', 'WriteMode', 'append', 'DelayTime', 0.05);
    end
end

fprintf('GIF анімацію успішно збережено: %s\n', gif_name);